docs: adding changeloguru projects to next and v1.0.0 content
conventional-commits/conventionalcommits.org pull request #353
Opened 2021-03-22 06:03 UTC by haunt98

2021-03-23 11:10 UTC, damianopetrungaro requested changes
Quick one :)

2021-03-23 11:10 UTC, damianopetrungaro commented on content/next/index.md
> +* [Changeloguru](https://github.com/haunt98/changeloguru): Auto generate changelog from convetional commits, written in Go.
```suggestion
* [Changeloguru](https://github.com/haunt98/changeloguru): Auto-generate changelog from conventional commits, written in Go.
```

2021-03-23 11:10 UTC, damianopetrungaro commented on content/v1.0.0/index.md
> +* [Changeloguru](https://github.com/haunt98/changeloguru): Auto generate changelog from convetional commits, written in Go.
```suggestion
* [Changeloguru](https://github.com/haunt98/changeloguru): Auto-generate changelog from conventional commits, written in Go.
```

2021-03-24 04:04 UTC, haunt98 commented
Hi @damianopetrungaro, I have update PR follow your changes, can you please take a look ?

2021-04-01 10:44 UTC, merged