Introduce Ukrainian language
conventional-commits/conventionalcommits.org pull request #376
Opened 2021-06-17 16:19 UTC by podarok

Work in Progres

2021-06-17 17:33 UTC, podarok commented
Please, review @damianopetrungaro )))

2021-06-18 07:48 UTC, damianopetrungaro commented
Noice!
Thanks @podarok !

2021-06-18 17:24 UTC, podarok commented
@damianopetrungaro done. Please check

2021-06-19 13:35 UTC, anprok requested changes

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +Додаткові типи не заборонені угодою про Політику Комітів, і не накладають додаткові умови в Семантичних Версія ( окрім випадків коли вони містять BREAKING CHANGE).
Прибрати пробіл після дужки (

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +BREAKING CHANGE може бути частиною будь якого _type_.
будь якого пишеться з дефісом.

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +6. Довге тіло коміту MAY(може) бути додано після короткого опису, надаючи додаткову контекстру інформацію про зміни в коді. Тіло MUST(повинне) починатися з однієї пустої строки після опису.
Неправильне слово "контекстру"

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +7. Тіло коміту - це вільна форма і може містити будь яку кількість нових рядків і параграфів.
будь яку через дефіс

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +7. Тіло коміту - це вільна форма і може містити будь яку кількість нових рядків і параграфів.
"параграфів" замінити на "абзаців"

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +16. Одиниці інформаціх, що роблять Політику Комітів MUST NOT(не повинні) бути сприйняті як чутливими до регістру творцями інструментів, за виключенням BREAKING CHANGE, що MUST(мусить) бути великими л
інформаціх - інформації

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +Рекомендуємо продовжувати так, наче ви вже створили реліз продукту. Типічно *хтось*, навіть, якщо це ваші розробники, вже використовують ваше програмне забезпечення. Вони будуть знати, що виправлено,
Типічно - типово

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +Будь які можуть використовуватися, вле варто притримуватися якогось одного підходу.
Будь які через дефіс

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +Зробіть декілька комітів, наскільки це можливо. Частина вигоди від Політики Комітів є можливіть спонукати нас робити більш організовані коміти і PR/MRs
можливіть - можливість

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +Коміт містить наступні елементи структури, для спілкування інтенціх для споживачів
інтенціх?

2021-06-19 13:35 UTC, anprok commented on content/v1.0.0/index.uk.md
> +* Запуск процесів компіляції та публіації.
публікації

2021-06-19 14:10 UTC, podarok commented on content/v1.0.0/index.uk.md
> +* Запуск процесів компіляції та публіації.
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:10 UTC, podarok commented on content/v1.0.0/index.uk.md
> +Коміт містить наступні елементи структури, для спілкування інтенціх для споживачів
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:10 UTC, podarok commented on content/v1.0.0/index.uk.md
> +Зробіть декілька комітів, наскільки це можливо. Частина вигоди від Політики Комітів є можливіть спонукати нас робити більш організовані коміти і PR/MRs
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:10 UTC, podarok commented on content/v1.0.0/index.uk.md
> +Будь які можуть використовуватися, вле варто притримуватися якогось одного підходу.
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:10 UTC, podarok commented on content/v1.0.0/index.uk.md
> +Рекомендуємо продовжувати так, наче ви вже створили реліз продукту. Типічно *хтось*, навіть, якщо це ваші розробники, вже використовують ваше програмне забезпечення. Вони будуть знати, що виправлено,
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:10 UTC, podarok commented on content/v1.0.0/index.uk.md
> +16. Одиниці інформаціх, що роблять Політику Комітів MUST NOT(не повинні) бути сприйняті як чутливими до регістру творцями інструментів, за виключенням BREAKING CHANGE, що MUST(мусить) бути великими л
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:10 UTC, podarok commented on content/v1.0.0/index.uk.md
> +7. Тіло коміту - це вільна форма і може містити будь яку кількість нових рядків і параграфів.
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:10 UTC, podarok commented on content/v1.0.0/index.uk.md
> +6. Довге тіло коміту MAY(може) бути додано після короткого опису, надаючи додаткову контекстру інформацію про зміни в коді. Тіло MUST(повинне) починатися з однієї пустої строки після опису.
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:10 UTC, podarok commented on content/v1.0.0/index.uk.md
> +BREAKING CHANGE може бути частиною будь якого _type_.
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:11 UTC, podarok commented on content/v1.0.0/index.uk.md
> +Додаткові типи не заборонені угодою про Політику Комітів, і не накладають додаткові умови в Семантичних Версія ( окрім випадків коли вони містять BREAKING CHANGE).
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

2021-06-19 14:11 UTC, podarok commented
Thanks for the review @anprok 
solved https://github.com/conventional-commits/conventionalcommits.org/pull/376/commits/9f91fe0ec5e183296c52da31b2a2d722a909a07a

@damianopetrungaro I guess it is ready now

2021-06-24 09:37 UTC, merged

2021-06-24 09:37 UTC, damianopetrungaro commented
Thanks for the hard work @podarok !
Merged :)

2021-06-24 14:17 UTC, podarok commented
Thank you @damianopetrungaro 
It's already on a site, confirmed all good