docs(about): add `EasyBuild` projects to the list of tools
conventional-commits/conventionalcommits.org pull request #622
Opened 2024-11-19 15:59 UTC by MangelMaxime

Hello,

For the past few months I explored using Convention Commits in my project and because I have a lot of OSS projects to maintains I made a collection of tools.

They are mostly aimed at .NET developers because they are published as `dotnet tool` but they can be used by any one.

2024-12-27 14:48 UTC, bcoe approved these changes

2024-12-27 14:48 UTC, merged

2024-12-27 14:48 UTC, bcoe commented
Thank you for the contribution @MangelMaxime.

2025-03-15 02:10 UTC, dimu783 reviewed
9d72475f35bc069a3bf8a3180f99c95e3399df20

2025-03-22 05:37 UTC, R4M4NCHICK1 approved these changes

2025-03-22 05:38 UTC, R4M4NCHICK1 requested changes
R